[build]
  # Directory to change to before starting a build
  base = "."
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "dist"
  
  # Default build command
  command = "npm run build"

[build.environment]
  # Set Node.js version
  NODE_VERSION = "18"
  
  # Increase memory limit for build process
  NODE_OPTIONS = "--max-old-space-size=4096"

# Redirect rules for Single Page Application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  
# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://accounts.google.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://odoo336-akhta2hvagf3czda.southindia-01.azurewebsites.net https://accounts.google.com; frame-src https://accounts.google.com;"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache HTML with shorter duration
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Handle JavaScript modules with correct MIME type
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.mjs"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.jsx"
  [headers.values]
    Content-Type = "application/javascript"

# API proxy for development (optional - you might not need this since you're using direct API calls)
# [[redirects]]
#   from = "/api/*"
#   to = "https://odoo336-akhta2hvagf3czda.southindia-01.azurewebsites.net/:splat"
#   status = 200
#   force = true