name: Build and Push Docker Image

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  DOCKER_USERNAME: 23f2005217
  IMAGE_NAME: odoo

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for proper versioning
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Generate version
      id: version
      run: |
        COMMIT_COUNT=$(git rev-list --count HEAD)
        GIT_COMMIT=$(git rev-parse --short HEAD)
        BUILD_DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)
        APP_VERSION="1.0.${COMMIT_COUNT}"
        
        echo "app_version=${APP_VERSION}" >> $GITHUB_OUTPUT
        echo "git_commit=${GIT_COMMIT}" >> $GITHUB_OUTPUT
        echo "build_date=${BUILD_DATE}" >> $GITHUB_OUTPUT
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.app_version }}
          ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
        build-args: |
          APP_VERSION=${{ steps.version.outputs.app_version }}
          BUILD_DATE=${{ steps.version.outputs.build_date }}
          GIT_COMMIT=${{ steps.version.outputs.git_commit }}
          DOCKER_TAG=${{ steps.version.outputs.app_version }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Output image details
      run: |
        echo "✅ Successfully built and pushed:"
        echo "🏷️  ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.app_version }}"
        echo "🏷️  ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest"
        echo "🔗 https://hub.docker.com/r/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}/tags"
